version: "3.8"

services:
  frontend:
    build: .
    container_name: knot-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8080
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
