version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: knot-postgres
    environment:
      POSTGRES_DB: knot_backend
      POSTGRES_USER: knot
      POSTGRES_PASSWORD: knot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knot -d knot_backend"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: knot-backend
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./alembic:/knot-backend/alembic
      - ./knot_backend:/knot-backend/knot_backend
    command: >
      sh -c "
        echo 'Waiting for database to be ready...' &&
        poetry run alembic upgrade head &&
        echo 'Database migrations completed. Starting server...' &&
        poetry run uvicorn knot_backend.app:app --host 0.0.0.0 --port 8080 --timeout-keep-alive 625 --workers 2 --loop uvloop --header server:TI-84 --no-access-log
      "

volumes:
  postgres_data: