"""create_contact_history_tables

Revision ID: 7274974d5601
Revises: a54c4ce1e1f3
Create Date: 2025-10-16 01:47:52.805106+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7274974d5601'
down_revision: Union[str, Sequence[str], None] = 'a54c4ce1e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contact_histories',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('contact_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('field_changed', sa.String(length=50), nullable=True),
        sa.Column('old_value', sa.Text(), nullable=True),
        sa.Column('new_value', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_contact_history_contact_id', 'contact_histories', ['contact_id'], unique=False)
    op.create_index('idx_contact_history_created_at', 'contact_histories', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_contact_history_created_at', table_name='contact_histories')
    op.drop_index('idx_contact_history_contact_id', table_name='contact_histories')
    op.drop_table('contact_histories')
    # ### end Alembic commands ###
